# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    env:
      ACCESS_TOKEN:  ${{ secrets.ACCESS_TOKEN }}
      URL: https://${ACCESS_TOKEN}@github.com/aewshyae/aozorabunko-re-design_pages.git
      BRANCH: master
      CLONE_DIR: $(mktemp -d)
      NUXT_ENV_PERSON_DETAIL_URL: https://raw.githubusercontent.com/takahashim/aozora_json_scrape/master/person_detail.json
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name : build
        run: |
          npm ci
          npm run build
          npm run test
          npm run generate
      - run: ls -1a dist
      - name: github setup
        run: |
          git config --global user.email "1528058+aewshyae@users.noreply.github.com"
          git config --global user.name "aewshyae"
          echo "$CLONE_DIR"
      - name: clone and replace with dist
        run: |
          git clone --depth 1 ${URL} ${CLONE_DIR}
          echo "--cloned"
          ls -1a
          find "$CLONE_DIR" | grep -v "^$CLONE_DIR/\.git" | grep -v "^$CLONE_DIR$" | xargs rm -rf
          echo "--deleted"
          ls -1a "$CLONE_DIR"
          cp -r dist/* "$CLONE_DIR"
      - name: commit
        run: |
          cd ${CLONE_DIR}
          git add .
          git commit --message "Update from $GITHUB_REPOSITORY by github action"
          echo "--commited"
      - name: deploy
        run: |
          git push origin ${BRANCH}
