# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    env:
      ACCESS_TOKEN:  ${{ secrets.ACCESS_TOKEN }}
      URL: https://x-access-token:${ACCESS_TOKEN}@github.com/aewshyae/aozorabunko-re-design_pages
      BRANCH: master
      CLONE_DIR: tmp
      NUXT_ENV_PERSON_DETAIL_URL: https://raw.githubusercontent.com/takahashim/aozora_json_scrape/master/person_detail.json
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run generate
      - run: ls -la
      # deploy
      - run: git clone --depth 1 ${URL} ${CLONE_DIR}
      - run: ls -la
      - run: find ${CLONE_DIR} | grep -v "${CLONE_DIR}"| grep -v "${CLONE_DIR}/.git" | grep -v "^\.*$" | xargs rm -rf 
      - run: ls -la
      - run: cp -r dist/ ${CLONE_DIR}/
      - run: ls -la ${CLONE_DIR}
      - run: cd ${CLONE_DIR} && git add . && git commit --message "Update from $GITHUB_REPOSITORY github action" && git push ${URL} ${BRANCH}
